Make OpenAI API endpoint configurable
karthink/gptel pull request #49
Opened 2023-04-28 15:41 UTC by christianromney

Also encode stream :json-false when stream is nil
since the API requires a boolean value (https://platform.openai.com/docs/api-reference/chat).

Signed-off-by: Christian Romney <christian.romney@nubank.com.br>

2023-04-28 15:44 UTC, christianromney commented
Hi! I really like the user experience of your package. I prefer it to the chatgpt package from emacs-openai. I had a problem where I needed to send requests through a (non-system-wide) proxy which led me to add the base uri as a custom var. I also force the json-encoding of stream to a boolean value as indicated by the API documentation. Thanks for sharing your package!

2023-04-29 03:47 UTC, karthink requested changes
Thank you! Please see the review comments.

2023-04-29 03:47 UTC, karthink commented on gptel.el
> +           :stream ,(or (and gptel-stream gptel-use-curl) :json-false))))
Thanks, I was fuzzy about the difference between `nil` and `:json-false`.

Could you make just this change the first commit?

2023-04-29 03:47 UTC, karthink commented on README.org
> +- You can override the OpenAI API endpoint by customizing ~gptel-openai-endpoint~.
Replace with `=gptel-openai-endpoint=`, as I use `=` delimiters for verbatim commands and `~` delimiters for notating keybindings. (There is no distinction between them in the Github renderer but these are different things when viewing this file in Emacs.)

2023-04-29 03:47 UTC, karthink commented on gptel.el
> +(defcustom gptel-openai-endpoint "https://api.openai.com/v1"
This definition needs a `:type 'string` annotation. While it's not required by Emacs, please also add a `:group 'gptel` annotation for consistency with the other definitions in this package.

2023-07-13 20:20 UTC, karthink commented
This has been superceded by #67.

2023-07-13 20:20 UTC, closed without merging